version: '3.8'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8090:8090" # qbittorrent
    volumes:
      - ./gluetun/custom-ovpn-files:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-s", "https://cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_proxy
      - internal
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - WEBUI_PORT=8090
    volumes:
      - ./data/qbittorrent/config:/config
      - ./data/downloads:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/media:/data/media
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./data/sonarr/config:/config
      - ./data/media/tv:/tv
      - ./data/downloads:/downloads
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./data/radarr/config:/config
      - ./data/media/movies:/movies
      - ./data/downloads:/downloads
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./data/prowlarr/config:/config
    restart: unless-stopped
    networks:
      - traefik_proxy
      - internal

networks:
  traefik_proxy:
    external: true
  internal:
    driver: bridge
